### ISSUE TITLE
Error: java.lang.NullPointerException

### ISSUE THREAD

**Issue by TCT9** [mixly/Mixly_Arduino#12]
Hello!

Hello!

I created a code like this using only blocks:

void setup(){
  pinMode(13, OUTPUT);
}

void loop(){
  digitalWrite(13,HIGH);
}

It returns the following error message when compiling:

java.lang.NullPointerException
	at org.mixly.Browser_new.compile(Browser_new.java:2090)
	at org.mixly.Browser_new.access$40(Browser_new.java:2035)
	at org.mixly.Browser_new$52.run(Browser_new.java:1655)
	at java.lang.Thread.run(Thread.java:748)

What should I do to fix this?

**Comment by macomzzl** [comment]
just re-download the latest software, it is a bug and now fix it.
